# Persistent Volume Template
apiVersion: v1
kind: PersistentVolume
metadata:
  name: synology-default
  namespace: jupyterhub
  labels:
    user: default
  
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: synology-default
    volumeAttributes:
      source: "//172.16.49.60/ml-storage"
    nodeStageSecretRef:
      name: secret-synology-default
      namespace: jupyterhub
      
---
# Persistent Volume Claim Template
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synology-default
  namespace: jupyterhub
spec:
  storageClassName: ""

  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
# Secret Template
apiVersion: v1
kind: Secret
metadata:
  name: secret-synology-default
  namespace: jupyterhub
  
type: Opaque
data:
  username: ZGVmYXVsdA==
  password: QWJjZDEyMzQ=
