# Persistent Volume Template
apiVersion: v1
kind: PersistentVolume
metadata:
  name: synology-trevor-schwantes---21096812
  namespace: jupyterhub
  labels:
    user: trevor-schwantes---21096812
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: synology-trevor-schwantes---21096812
    volumeAttributes:
      source: "//172.16.49.55/Share"
    nodeStageSecretRef:
      name: secret-synology-trevor-schwantes---21096812
      namespace: jupyterhub

---
# Persistent Volume Claim Template
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synology-trevor-schwantes---21096812
  namespace: jupyterhub
spec:
  storageClassName: ""

  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---
# Secret Template
apiVersion: v1
kind: Secret
metadata:
  name: secret-synology-trevor-schwantes---21096812
  namespace: jupyterhub

type: Opaque
data:
  username: dHJldm9yLXNjaHdhbnRlcw==
  password: MUU5ZXg2Z2g=
