# Persistent Volume Template
apiVersion: v1
kind: PersistentVolume
metadata:
  name: synology-zubair-ahmad
  namespace: jupyterhub
  labels:
    user: zubair-ahmad
  
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: synology-zubair-ahmad
    volumeAttributes:
      source: "//172.16.49.55/Share"
    nodeStageSecretRef:
      name: secret-synology-zubair-ahmad
      namespace: jupyterhub
      
---
# Persistent Volume Claim Template
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synology-zubair-ahmad
  namespace: jupyterhub
spec:
  storageClassName: ""

  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
# Secret Template
apiVersion: v1
kind: Secret
metadata:
  name: secret-synology-zubair-ahmad
  namespace: jupyterhub
  
type: Opaque
data:
  username: enViYWlyLWFobWFk
  password: KTducVZTJzc=

