#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: kadalu-pv
#spec:
#  capacity:
#    storage: 6Ti
#  accessModes:
#    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: kadalu.local-data-storage
#  csi:
#    driver: kadalu
#    volumeAttributes:
#      storage_pool: local-data-storage



apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-local-data
  namespace: jupyterhub
spec:
  storageClassName: kadalu.local-data-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Ti


