apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: kadalu
  creationTimestamp: "2024-12-06T22:04:43Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-ecd26eb0-12a0-4678-8ff9-5f72802d730e
  resourceVersion: "2575"
  uid: d4e62962-dbd6-429a-a5f1-7ed26fd01b23
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 6Ti
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pvc-local-data
    namespace: jupyterhub
    resourceVersion: "1724"
    uid: ecd26eb0-12a0-4678-8ff9-5f72802d730e
  csi:
    driver: kadalu
    volumeAttributes:
      fstype: xfs
      gserver: 172.16.49.54,172.16.49.59
      gvolname: local-data
      hostvol: local-data
      options: log-level=DEBUG
      path: subvol/12/17/pvc-ecd26eb0-12a0-4678-8ff9-5f72802d730e
      pvtype: subvol
      single_pv_per_pool: "False"
      storage.kubernetes.io/csiProvisionerIdentity: 1733522677873-8081-kadalu
      type: External
    volumeHandle: pvc-ecd26eb0-12a0-4678-8ff9-5f72802d730e
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kadalu.local-data
  volumeMode: Filesystem
status:
  lastPhaseTransitionTime: "2024-12-06T22:04:43Z"
  phase: Bound
