apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"pvc-local-data","namespace":"jupyterhub"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"6Ti"}},"storageClassName":"kadalu.local-data"}}
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kadalu
    volume.kubernetes.io/storage-provisioner: kadalu
  creationTimestamp: "2024-12-06T22:04:20Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: pvc-local-data
  namespace: jupyterhub
  resourceVersion: "1796"
  uid: ecd26eb0-12a0-4678-8ff9-5f72802d730e
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 6Ti
  storageClassName: kadalu.local-data
  volumeMode: Filesystem
  volumeName: pvc-ecd26eb0-12a0-4678-8ff9-5f72802d730e
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 6Ti
  phase: Bound
