apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-manager-binding
  namespace: jupyterhub
subjects:
  - kind: ServiceAccount
    name: default  # The service account for which you're granting permissions
    namespace: jupyterhub
roleRef:
  kind: Role
  name: pod-manager  # The name of the role you're binding
  apiGroup: rbac.authorization.k8s.io
