apiVersion: v1
kind: Service
metadata:
  namespace: jupyterhub
  name: jupyterhub-routing-api
spec:
  type: NodePort
  ports:
  - port: 8001
    nodePort: 32123
    targetPort: 8001
  selector:
    app: jupyterhub
    component: proxy
    release: jupyterhub
