apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc  # This should match your JupyterHub config (pvcNameTemplate)
  namespace: jupyterhub
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: $NFS_STORAGE_SIZE  # Must match the size of the PV
  volumeName: shared-pv  # Bind directly to the PV
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc-conda  # Unique name for the PVC related to Conda
  namespace: jupyterhub
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: $NFS_STORAGE_SIZE  # Must match the size of the PV
  volumeName: shared-pv-conda  # Bind directly to the Conda PV
