apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-registry
spec:
  capacity:
    storage: $DOCKER_REGISTRY_SIZE
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: $DOCKER_REGISTRY_PATH
  storageClassName: ""  # Explicitly set no storage class
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: $DOCKER_REGISTRY_SIZE
  storageClassName: ""  # Ensure no storage class is assigned
