apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kadalu-replicated-pvc
  namespace: jupyterhub
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Ti
  storageClassName: kadalu.replicated-storage
