apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorboard
  labels:
    app: tensorboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tensorboard
  template:
    metadata:
      labels:
        app: tensorboard
    spec:
      containers:
      - name: tensorboard
        image: tensorflow/tensorflow:latest
        command:
          - /usr/local/bin/tensorboard
          - --logdir=/mnt/tensorboard_logs
          - --bind_all
        volumeMounts:
        - name: tensorboard-storage
          mountPath: /mnt/tensorboard_logs
      volumes:
      - name: tensorboard-storage
        persistentVolumeClaim:
          claimName: tensorboard-pvc
