apiVersion: v1
kind: PersistentVolume
metadata:
  name: tensorboard-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:  # Assuming NFS is used for shared storage
    path: /home/default/tmp_pv  # NFS mount path on the host
    server: 192.168.0.125  # NFS server IP
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jhub-storage-class
