hub:
  db:
    type: sqlite-memory
  config:
    Authenticator:
      admin_users:
        - admin
      allowed_users:
        - admin
    DummyAuthenticator:
      password: admin_password
    JupyterHub:
      authenticator_class: dummy
  authenticatePrometheus: false
  allowNamedServers: true
  namedServerLimitPerUser: 5

proxy:
  chp:
    networkPolicy:
      egress:
        - ports:
          - port: 6116
          - port: 6117
          - port: 6118

singleuser:
  uid: 1000
  serviceAccountName: default
  storage:
    type: static
    static:
      pvcName: "shared-pvc" 
      subPath: "{username}"
#      storageAccessModes: ["ReadWriteMany"]  
#      storageClass: "jhub-storage-class"  
      
    extraVolumes:
      - name: vol-synology-user
        persistentVolumeClaim:
          claimName: synology-{username}
    extraVolumeMounts:
      - name: vol-synology-user
        mountPath: "/home/jovyan/ml-storage"  # User data volume mount
        
#      pvcNameTemplate: "synology-{username}" 
#      storageClass: ""
#      storageAccessModes: ["ReadWriteMany"]  
  profileList:
    - display_name: "0 GPUs"
      kubespawner_override:
        image: 192.168.0.125:30000/base:latest
#        image: quay.io/jupyter/pytorch-notebook:latest
        image_pull_policy: Always
        extra_resource_limits:
          nvidia.com/gpu: "0"
        runtime_class_name: nvidia
      default: true
    - display_name: "1 GPU"
      kubespawner_override:
        image: 192.168.0.125:30000/base:latest
        image_pull_policy: Always
        extra_resource_limits:
          nvidia.com/gpu: "1"
        runtime_class_name: nvidia
    - display_name: "2 GPUs"
      kubespawner_override:
        image: 192.168.0.125:30000/base:latest
        image_pull_policy: Always
        extra_resource_limits:
          nvidia.com/gpu: "2"
        runtime_class_name: nvidia

  extraEnv:
    CONDA_PKGS_DIRS: /home/jovyan/conda_pkgs
    CONDA_ENVS_PATH: /home/jovyan/conda_envs
    GRANT_SUDO: "yes"
    NOTEBOOK_ARGS: "--allow-root"
#  uid: 0
#  cmd: start-singleuser.sh
  allowPrivilegeEscalation: true

