hub:
  db:
    type: sqlite-memory
  config:
    Authenticator:
      admin_users:
        - admin
        - matthew-arnold
        - trevor-schwantes
      allowed_users:
        - admin
        - matthew-arnold
        - trevor-schwantes
    DummyAuthenticator:
      password: Abcd1234
    JupyterHub:
      authenticator_class: dummy
  authenticatePrometheus: false
  allowNamedServers: true
  namedServerLimitPerUser: 5

proxy:
  chp:
    networkPolicy:
      egress:
        - ports:
          - port: 6116
          - port: 6117
          - port: 6118

singleuser:
  uid: 1000
  serviceAccountName: default
  storage:
    type: static
    static:
      pvcName: "shared-pvc" 
      subPath: "{username}"
      
    extraVolumes:
      - name: vol-synology-user
        persistentVolumeClaim:
          claimName: synology-{username}
      - name: conda-cache-pvc
        persistentVolumeClaim:
          claimName: shared-pvc-conda 
      - name: glusterfs-storage
        persistentVolumeClaim:
          claimName: glusterfs-pvc  # New GlusterFS PVC
    extraVolumeMounts:
      - name: conda-cache-pvc
        mountPath: /home/jovyan/.conda/pkgs
      - name: vol-synology-user
        mountPath: "/home/jovyan/ml-storage"  # User data volume mount
      - name: glusterfs-storage
        mountPath: "/home/jovyan/local-data"  # GlusterFS volume mount

  profileList:
    - display_name: "0 GPUs"
      kubespawner_override:
        image: 172.16.49.54:30000/base:latest   # image: quay.io/jupyter/pytorch-notebook:latest
        image_pull_policy: Always
        extra_resource_limits:
          nvidia.com/gpu: "0"
        runtime_class_name: nvidia
        hostNetwork: true
      default: true
    - display_name: "1 GPU"
      kubespawner_override:
        image: 172.16.49.54:30000/base:latest
        image_pull_policy: Always
        extra_resource_limits:
          nvidia.com/gpu: "1"
        runtime_class_name: nvidia
        hostNetwork: true
    - display_name: "2 GPUs"
      kubespawner_override:
        image: 172.16.49.54:30000/base:latest
        image_pull_policy: Always
        extra_resource_limits:
          nvidia.com/gpu: "2"
        runtime_class_name: nvidia
        hostNetwork: true

  extraEnv:
    CONDA_PKGS_DIRS: /home/jovyan/.conda/pkgs
    CONDA_ENVS_PATH: /home/jovyan/.conda/envs
    GRANT_SUDO: "yes"
    NOTEBOOK_ARGS: "--allow-root"
#  uid: 0
#  cmd: start-singleuser.sh
  allowPrivilegeEscalation: true

